// Generated by CosDI. Do not edit.
import type { IExampleService as IExampleService_ } from './assets/Scripts/IExampleService';

declare module 'cosdi' {
    interface ServiceTypes {
        'IExampleService': IExampleService_;
    }
}
